import { generateEnumContextFile } from '../../generators/contextGenerator';
import { EnumInfo } from '../../generators/enumGenerator';

describe('contextGenerator', () => {
    describe('generateEnumContextFile', () => {
        const mockEnums: EnumInfo[] = [
            {
                objectName: 'User',
                propertyName: 'status',
                values: [
                    { value: 'ACTIVE', label: 'Active' },
                    { value: 'INACTIVE', label: 'Inactive' },
                ],
            },
            {
                objectName: 'User',
                propertyName: 'role',
                values: [
                    { value: 'ADMIN', label: 'Administrator' },
                    { value: 'USER', label: 'User' },
                ],
            },
        ];

        it('should generate context with EnumOptions interface', () => {
            const output = generateEnumContextFile(mockEnums);

            expect(output).toContain("'use client';");
            expect(output).toContain('// Auto-generated by @omnifyjp/omnify');
            expect(output).toContain('export interface EnumOptions {');
            expect(output).toContain('status: Record<string, string>;');
            expect(output).toContain('role: Record<string, string>;');
            expect(output).toContain('prefectures: Record<string, string>;');
        });

        it('should generate STATIC_ENUMS object', () => {
            const output = generateEnumContextFile(mockEnums);

            expect(output).toContain('const STATIC_ENUMS: EnumOptions = {');
            expect(output).toContain('status: {');
            expect(output).toContain("ACTIVE: 'Active'");
            expect(output).toContain("INACTIVE: 'Inactive'");
            expect(output).toContain('role: {');
            expect(output).toContain("ADMIN: 'Administrator'");
            expect(output).toContain("USER: 'User'");
        });

        it('should include all 47 prefectures', () => {
            const output = generateEnumContextFile(mockEnums);

            expect(output).toContain('prefectures: {');
            expect(output).toContain("'1': '北海道'");
            expect(output).toContain("'13': '東京都'");
            expect(output).toContain("'47': '沖縄県'");
        });

        it('should generate EnumsContextType with helper methods', () => {
            const output = generateEnumContextFile(mockEnums);

            expect(output).toContain('interface EnumsContextType {');
            expect(output).toContain('enums: EnumOptions | null;');
            expect(output).toContain('loading: boolean;');
            expect(output).toContain('error: Error | null;');
            expect(output).toContain('getLabel: (enumKey: keyof EnumOptions, value: string | number) => string | undefined;');
            expect(output).toContain('getValue: (enumKey: keyof EnumOptions, label: string) => string | undefined;');
            expect(output).toContain('getOptions: (enumKey: keyof EnumOptions) => { value: string; label: string }[];');
        });

        it('should generate EnumsProvider component', () => {
            const output = generateEnumContextFile(mockEnums);

            expect(output).toContain('export function EnumsProvider({ children }: { children: ReactNode })');
            expect(output).toContain('const [enums] = useState<EnumOptions>(STATIC_ENUMS);');
            expect(output).toContain('<EnumsContext.Provider');
        });

        it('should generate getLabel helper method', () => {
            const output = generateEnumContextFile(mockEnums);

            expect(output).toContain('const getLabel = (enumKey: keyof EnumOptions, value: string | number): string | undefined => {');
            expect(output).toContain('if (!enums) return undefined;');
            expect(output).toContain('const enumData = enums[enumKey];');
            expect(output).toContain('return enumData[String(value)];');
        });

        it('should generate getValue helper method', () => {
            const output = generateEnumContextFile(mockEnums);

            expect(output).toContain('const getValue = (enumKey: keyof EnumOptions, label: string): string | undefined => {');
            expect(output).toContain('return Object.entries(enumData).find(([_, l]) => l === label)?.[0];');
        });

        it('should generate getOptions helper method', () => {
            const output = generateEnumContextFile(mockEnums);

            expect(output).toContain('const getOptions = (enumKey: keyof EnumOptions): { value: string; label: string }[] => {');
            expect(output).toContain('return Object.entries(enumData).map(([value, label]) => ({ value, label }));');
        });

        it('should generate useEnums hook', () => {
            const output = generateEnumContextFile(mockEnums);

            expect(output).toContain('export function useEnums(): EnumsContextType {');
            expect(output).toContain('const context = useContext(EnumsContext);');
            expect(output).toContain("throw new Error('useEnums must be used within an EnumsProvider');");
        });

        it('should handle empty enums array', () => {
            const output = generateEnumContextFile([]);

            expect(output).toContain('export interface EnumOptions {');
            expect(output).toContain('prefectures: Record<string, string>;');
            expect(output).toContain('const STATIC_ENUMS: EnumOptions = {');
        });
    });
});

