import { extractEnums, generateEnumsFile } from '../../generators/enumGenerator';
import { SchemaLock, Property } from '../../types';

describe('enumGenerator', () => {
    const mockSchema = {
        User: {
            name: 'User',
            table: 'users',
            properties: {
                id: {
                    type: 'Id',
                    objectName: 'User',
                    propertyName: 'id',
                    displayName: 'ID',
                    description: null,
                    primary: true,
                } as Property,
                status: {
                    type: 'Enum',
                    enum: [
                        { value: 'ACTIVE', label: 'Active' },
                        { value: 'INACTIVE', label: 'Inactive' },
                    ],
                    objectName: 'User',
                    propertyName: 'status',
                    displayName: 'Status',
                    description: null,
                } as Property,
                role: {
                    type: 'Enum',
                    enum: [
                        { value: 'ADMIN', label: 'Administrator' },
                        { value: 'USER', label: 'User' },
                    ],
                    objectName: 'User',
                    propertyName: 'role',
                    displayName: 'Role',
                    description: null,
                } as Property,
            },
        },
    } as any;

    describe('extractEnums', () => {
        it('should extract all enums from schema', () => {
            const enums = extractEnums(mockSchema);

            expect(enums).toHaveLength(2);
            expect(enums[0].objectName).toBe('User');
            expect(enums[0].propertyName).toBe('status');
            expect(enums[0].values).toHaveLength(2);
            expect(enums[1].propertyName).toBe('role');
        });

        it('should handle schema with no enums', () => {
            const schemaWithoutEnums = {
                User: {
                    name: 'User',
                    table: 'users',
                    properties: {
                        id: {
                            type: 'Id',
                            objectName: 'User',
                            propertyName: 'id',
                            displayName: 'ID',
                            description: null,
                        } as Property,
                        name: {
                            type: 'String',
                            objectName: 'User',
                            propertyName: 'name',
                            displayName: 'Name',
                            description: null,
                        } as Property,
                    },
                },
            } as any;

            const enums = extractEnums(schemaWithoutEnums);
            expect(enums).toHaveLength(0);
        });
    });

    describe('generateEnumsFile', () => {
        it('should generate enums file with types and options', () => {
            const enums = extractEnums(mockSchema);
            const output = generateEnumsFile(enums);

            expect(output).toContain('// Auto-generated by @omnifyjp/omnify');

            // Check enum types (PascalCase)
            expect(output).toContain('export type UserStatus');
            expect(output).toContain("| 'ACTIVE'");
            expect(output).toContain("| 'INACTIVE'");
            expect(output).toContain('export type UserRole');
            expect(output).toContain("| 'ADMIN'");
            expect(output).toContain("| 'USER'");

            // Check enum options
            expect(output).toContain('export const statusOptions = {');
            expect(output).toContain("ACTIVE: 'Active'");
            expect(output).toContain("INACTIVE: 'Inactive'");
            expect(output).toContain('export const roleOptions = {');
            expect(output).toContain("ADMIN: 'Administrator'");
            expect(output).toContain("USER: 'User'");
        });

        it('should preserve mixed-case words in PascalCase conversion', () => {
            const mixedCaseSchema = {
                ApplicationForm: {
                    name: 'ApplicationForm',
                    table: 'application_forms',
                    properties: {
                        id: {
                            type: 'Id',
                            objectName: 'ApplicationForm',
                            propertyName: 'id',
                            displayName: 'ID',
                            description: null,
                        } as Property,
                        entity_type: {
                            type: 'Enum',
                            enum: [
                                { value: 'CORPORATION', label: 'Corporation' },
                            ],
                            objectName: 'ApplicationForm',
                            propertyName: 'entity_type',
                            displayName: 'Entity Type',
                            description: null,
                        } as Property,
                    },
                },
            } as any;

            const enums = extractEnums(mixedCaseSchema);
            const output = generateEnumsFile(enums);

            // Should preserve "ApplicationForm" not convert to "Applicationform"
            expect(output).toContain('export type ApplicationFormEntityType');
            expect(output).not.toContain('ApplicationformEntityType');
        });

        it('should have clear section separators', () => {
            const enums = extractEnums(mockSchema);
            const output = generateEnumsFile(enums);

            expect(output).toContain('// ============================================');
            expect(output).toContain('// Enum Types');
            expect(output).toContain('// Enum Options (Value -> Label mappings)');
        });

        it('should use "as const" for enum options', () => {
            const enums = extractEnums(mockSchema);
            const output = generateEnumsFile(enums);

            expect(output).toContain('} as const;');
        });

        it('should generate empty file for no enums', () => {
            const output = generateEnumsFile([]);
            expect(output).toContain('// Auto-generated by @omnifyjp/omnify');
            expect(output).not.toContain('export type');
            expect(output).not.toContain('export const');
        });
    });
});

