import { generateModelFile, generateExtendedModelFile, generateModelsIndexFile, generateAllModels } from '../../generators/modelGenerator';
import { OmnifyObject, Property, SchemaLock } from '../../types';

describe('modelGenerator', () => {
    describe('generateModelFile', () => {
        it('should generate basic model interface', () => {
            const object = {
                name: 'User',
                table: 'users',
                label: 'User',
                properties: {
                    id: {
                        type: 'Id',
                        objectName: 'User',
                        propertyName: 'id',
                        displayName: 'ID',
                        description: null,
                        primary: true,
                    } as Property,
                    name: {
                        type: 'String',
                        objectName: 'User',
                        propertyName: 'name',
                        displayName: 'Name',
                        description: null,
                    } as Property,
                    email: {
                        type: 'Email',
                        objectName: 'User',
                        propertyName: 'email',
                        displayName: 'Email',
                        description: null,
                    } as Property,
                },
            } as any;

            const output = generateModelFile('User', object, false);

            expect(output).toContain('// Auto-generated by @famgia/omnify');
            expect(output).toContain('export interface User {');
            expect(output).toContain('id: number; // ID');
            expect(output).toContain('name: string; // Name');
            expect(output).toContain('email: string; // Email');
        });

        it('should handle nullable fields', () => {
            const object = {
                name: 'User',
                table: 'users',
                properties: {
                    id: {
                        type: 'Id',
                        objectName: 'User',
                        propertyName: 'id',
                        displayName: 'ID',
                        description: null,
                    } as Property,
                    bio: {
                        type: 'Text',
                        nullable: true,
                        objectName: 'User',
                        propertyName: 'bio',
                        displayName: 'Bio',
                        description: null,
                    } as Property,
                },
            } as any;

            const output = generateModelFile('User', object, false);

            expect(output).toContain('bio?: string | null;');
        });

        it('should handle enum fields', () => {
            const object = {
                name: 'User',
                table: 'users',
                properties: {
                    id: {
                        type: 'Id',
                        objectName: 'User',
                        propertyName: 'id',
                        displayName: 'ID',
                        description: null,
                    } as Property,
                    status: {
                        type: 'Enum',
                        enum: [
                            { value: 'ACTIVE', label: 'Active' },
                            { value: 'INACTIVE', label: 'Inactive' },
                        ],
                        objectName: 'User',
                        propertyName: 'status',
                        displayName: 'Status',
                        description: null,
                    } as Property,
                },
            } as any;

            const output = generateModelFile('User', object, false);

            expect(output).toContain('status: UserStatus;');
        });

        it('should use PascalCase for enum type names', () => {
            const object = {
                name: 'ApplicationForm',
                table: 'application_forms',
                properties: {
                    id: {
                        type: 'Id',
                        objectName: 'ApplicationForm',
                        propertyName: 'id',
                        displayName: 'ID',
                        description: null,
                    } as Property,
                    entity_type: {
                        type: 'Enum',
                        enum: [
                            { value: 'CORPORATION', label: 'Corporation' },
                        ],
                        objectName: 'ApplicationForm',
                        propertyName: 'entity_type',
                        displayName: 'Entity Type',
                        description: null,
                    } as Property,
                },
            } as any;

            const output = generateModelFile('ApplicationForm', object, false);

            // Should use PascalCase: ApplicationFormEntityType
            expect(output).toContain('entity_type: ApplicationFormEntityType;');
            expect(output).not.toContain('entity_type: ApplicationForm_entity_type;');
        });

        it('should preserve mixed-case in model enum references', () => {
            const object = {
                name: 'MyCustomModel',
                table: 'my_custom_models',
                properties: {
                    id: {
                        type: 'Id',
                        objectName: 'MyCustomModel',
                        propertyName: 'id',
                        displayName: 'ID',
                        description: null,
                    } as Property,
                    status: {
                        type: 'Enum',
                        enum: [
                            { value: 'ACTIVE', label: 'Active' },
                        ],
                        objectName: 'MyCustomModel',
                        propertyName: 'status',
                        displayName: 'Status',
                        description: null,
                    } as Property,
                },
            } as any;

            const output = generateModelFile('MyCustomModel', object, false);

            expect(output).toContain('status: MyCustomModelStatus;');
        });

        it('should generate clean output', () => {
            const object = {
                name: 'TestModel',
                table: 'test_models',
                properties: {
                    id: {
                        type: 'Id',
                        objectName: 'TestModel',
                        propertyName: 'id',
                        displayName: 'ID',
                        description: null,
                    } as Property,
                },
            } as any;

            const output = generateModelFile('TestModel', object, false);

            expect(output).not.toContain('undefined');
            expect(output).not.toContain('[object Object]');
        });

        it('should generate base models with Base prefix when useBasePrefix is true', () => {
            const object = {
                name: 'User',
                table: 'users',
                properties: {
                    id: {
                        type: 'Id',
                        objectName: 'User',
                        propertyName: 'id',
                        displayName: 'ID',
                        description: null,
                    } as Property,
                },
            } as any;

            const output = generateModelFile('User', object, true);

            expect(output).toContain('export interface BaseUser {');
            expect(output).not.toContain('export interface User {');
        });
    });

    describe('generateAllModels', () => {
        it('should generate all base models with Base prefix', () => {
            const schema = {
                User: {
                    objectName: 'User',
                    displayName: 'User',
                    properties: {
                        id: {
                            type: 'Id',
                            objectName: 'User',
                            propertyName: 'id',
                            displayName: 'ID',
                            description: null,
                        } as Property,
                    },
                },
                Company: {
                    objectName: 'Company',
                    displayName: 'Company',
                    properties: {
                        id: {
                            type: 'Id',
                            objectName: 'Company',
                            propertyName: 'id',
                            displayName: 'ID',
                            description: null,
                        } as Property,
                    },
                },
            } as any;

            const output = generateAllModels(schema);

            expect(output).toContain('// Auto-generated by @famgia/omnify');
            expect(output).toContain('// These are BASE models - DO NOT EDIT');
            expect(output).toContain('export interface BaseUser {');
            expect(output).toContain('export interface BaseCompany {');
            expect(output).not.toContain('export interface User {');
            expect(output).not.toContain('export interface Company {');
        });

        it('should import enums module', () => {
            const schema = {
                User: {
                    objectName: 'User',
                    displayName: 'User',
                    properties: {},
                },
            } as any;

            const output = generateAllModels(schema);

            expect(output).toContain("import * as Enums from './enums';");
        });
    });

    describe('generateExtendedModelFile', () => {
        it('should generate extended model file that extends base model', () => {
            const output = generateExtendedModelFile('User');

            expect(output).toContain('// Extended model for User');
            expect(output).toContain('// You can customize this file - it will not be overwritten');
            expect(output).toContain("import { BaseUser } from '../types/models';");
            expect(output).toContain('export interface User extends BaseUser {');
            expect(output).toContain('// Add your custom fields here');
        });

        it('should include example usage comments', () => {
            const output = generateExtendedModelFile('Company');

            expect(output).toContain('// Example:');
            expect(output).toContain('// customField?: string;');
            expect(output).toContain('// export function createCompany');
        });
    });

    describe('generateModelsIndexFile', () => {
        it('should generate index file that exports all models', () => {
            const objectNames = ['User', 'Company', 'Shop'];
            const output = generateModelsIndexFile(objectNames);

            expect(output).toContain('// Auto-generated by @famgia/omnify');
            expect(output).toContain("export * from './User';");
            expect(output).toContain("export * from './Company';");
            expect(output).toContain("export * from './Shop';");
        });
    });
});
