import { generateModelFile } from '../../generators/modelGenerator';
import { OmnifyObject, Property } from '../../types';

describe('modelGenerator', () => {
    describe('generateModelFile', () => {
        it('should generate basic model interface', () => {
            const object = {
                name: 'User',
                table: 'users',
                label: 'User',
                properties: {
                    id: {
                        type: 'Id',
                        objectName: 'User',
                        propertyName: 'id',
                        displayName: 'ID',
                        description: null,
                        primary: true,
                    } as Property,
                    name: {
                        type: 'String',
                        objectName: 'User',
                        propertyName: 'name',
                        displayName: 'Name',
                        description: null,
                    } as Property,
                    email: {
                        type: 'Email',
                        objectName: 'User',
                        propertyName: 'email',
                        displayName: 'Email',
                        description: null,
                    } as Property,
                },
            } as any;

            const output = generateModelFile('User', object);

            expect(output).toContain('// Auto-generated by @omnifyjp/omnify');
            expect(output).toContain('export interface User {');
            expect(output).toContain('id: number; // ID');
            expect(output).toContain('name: string; // Name');
            expect(output).toContain('email: string; // Email');
        });

        it('should handle nullable fields', () => {
            const object = {
                name: 'User',
                table: 'users',
                properties: {
                    id: {
                        type: 'Id',
                        objectName: 'User',
                        propertyName: 'id',
                        displayName: 'ID',
                        description: null,
                    } as Property,
                    bio: {
                        type: 'Text',
                        nullable: true,
                        objectName: 'User',
                        propertyName: 'bio',
                        displayName: 'Bio',
                        description: null,
                    } as Property,
                },
            } as any;

            const output = generateModelFile('User', object);

            expect(output).toContain('bio?: string | null;');
        });

        it('should handle enum fields', () => {
            const object = {
                name: 'User',
                table: 'users',
                properties: {
                    id: {
                        type: 'Id',
                        objectName: 'User',
                        propertyName: 'id',
                        displayName: 'ID',
                        description: null,
                    } as Property,
                    status: {
                        type: 'Enum',
                        enum: [
                            { value: 'ACTIVE', label: 'Active' },
                            { value: 'INACTIVE', label: 'Inactive' },
                        ],
                        objectName: 'User',
                        propertyName: 'status',
                        displayName: 'Status',
                        description: null,
                    } as Property,
                },
            } as any;

            const output = generateModelFile('User', object);

            expect(output).toContain('status: UserStatus;');
        });

        it('should use PascalCase for enum type names', () => {
            const object = {
                name: 'ApplicationForm',
                table: 'application_forms',
                properties: {
                    id: {
                        type: 'Id',
                        objectName: 'ApplicationForm',
                        propertyName: 'id',
                        displayName: 'ID',
                        description: null,
                    } as Property,
                    entity_type: {
                        type: 'Enum',
                        enum: [
                            { value: 'CORPORATION', label: 'Corporation' },
                        ],
                        objectName: 'ApplicationForm',
                        propertyName: 'entity_type',
                        displayName: 'Entity Type',
                        description: null,
                    } as Property,
                },
            } as any;

            const output = generateModelFile('ApplicationForm', object);

            // Should use PascalCase: ApplicationFormEntityType
            expect(output).toContain('entity_type: ApplicationFormEntityType;');
            expect(output).not.toContain('entity_type: ApplicationForm_entity_type;');
        });

        it('should preserve mixed-case in model enum references', () => {
            const object = {
                name: 'MyCustomModel',
                table: 'my_custom_models',
                properties: {
                    id: {
                        type: 'Id',
                        objectName: 'MyCustomModel',
                        propertyName: 'id',
                        displayName: 'ID',
                        description: null,
                    } as Property,
                    status: {
                        type: 'Enum',
                        enum: [
                            { value: 'ACTIVE', label: 'Active' },
                        ],
                        objectName: 'MyCustomModel',
                        propertyName: 'status',
                        displayName: 'Status',
                        description: null,
                    } as Property,
                },
            } as any;

            const output = generateModelFile('MyCustomModel', object);

            expect(output).toContain('status: MyCustomModelStatus;');
        });

        it('should generate clean output', () => {
            const object = {
                name: 'TestModel',
                table: 'test_models',
                properties: {
                    id: {
                        type: 'Id',
                        objectName: 'TestModel',
                        propertyName: 'id',
                        displayName: 'ID',
                        description: null,
                    } as Property,
                },
            } as any;

            const output = generateModelFile('TestModel', object);

            expect(output).not.toContain('undefined');
            expect(output).not.toContain('[object Object]');
        });
    });
});
