/**
 * Generate common/utility types (Laravel standard types, etc.)
 */
export function generateCommonTypes(): string {
  const lines: string[] = [];
  
  lines.push('// Auto-generated by @famgia/omnify');
  lines.push('// Common types (Laravel pagination, etc.)');
  lines.push('');
  lines.push('/**');
  lines.push(' * Laravel Pagination Response');
  lines.push(' */');
  lines.push('export interface PaginatedResponse<T> {');
  lines.push('  data: T[];');
  lines.push('  current_page: number;');
  lines.push('  last_page: number;');
  lines.push('  per_page: number;');
  lines.push('  total: number;');
  lines.push('  from: number | null;');
  lines.push('  to: number | null;');
  lines.push('  first_page_url: string;');
  lines.push('  last_page_url: string;');
  lines.push('  next_page_url: string | null;');
  lines.push('  prev_page_url: string | null;');
  lines.push('  path: string;');
  lines.push('  links: Array<{');
  lines.push('    url: string | null;');
  lines.push('    label: string;');
  lines.push('    active: boolean;');
  lines.push('  }>;');
  lines.push('}');
  lines.push('');
  
  return lines.join('\n');
}

