import { EnumInfo } from './enumGenerator';

export function generateEnumContextFile(enums: EnumInfo[]): string {
  const lines: string[] = [];

  lines.push("'use client';");
  lines.push('');
  lines.push('// Auto-generated by @famgia/omnify');
  lines.push('// Do not edit this file manually');
  lines.push('');
  lines.push("import React, { createContext, useContext, useState, useCallback, ReactNode } from 'react';");
  lines.push('');

  // Group by objectName for nested structure
  const enumsByObject = new Map<string, Map<string, EnumInfo>>();
  for (const enumInfo of enums) {
    if (!enumsByObject.has(enumInfo.objectName)) {
      enumsByObject.set(enumInfo.objectName, new Map());
    }
    enumsByObject.get(enumInfo.objectName)!.set(enumInfo.propertyName, enumInfo);
  }

  // Generate nested EnumOptions interface (only schema enums)
  lines.push('export interface EnumOptions {');
  for (const [objectName, propsMap] of enumsByObject.entries()) {
    lines.push(`  ${objectName}: {`);
    for (const propertyName of propsMap.keys()) {
      lines.push(`    ${propertyName}: Record<string, string>;`);
    }
    lines.push('  };');
  }
  lines.push('}');
  lines.push('');

  // Generate type-safe unions for IDE autocomplete
  lines.push('// Type-safe keys for IDE autocomplete');
  const allObjectNames = Array.from(enumsByObject.keys());
  lines.push(`export type EnumObjectName = ${allObjectNames.map(n => `'${n}'`).join(' | ')};`);
  lines.push('');

  // Generate property name unions per object
  for (const [objectName, propsMap] of enumsByObject.entries()) {
    const propNames = Array.from(propsMap.keys());
    lines.push(`export type ${objectName}EnumProperty = ${propNames.map(p => `'${p}'`).join(' | ')};`);
  }
  lines.push('');

  // Generate conditional type for property names based on object name
  lines.push('// Conditional type to get property names for each object');
  lines.push('export type EnumPropertyName<T extends EnumObjectName> = T extends keyof EnumOptions ? keyof EnumOptions[T] : never;');
  lines.push('');

  // Generate prefectures data (separate from schema enums)
  lines.push('const PREFECTURES: Record<string, string> = {');
  const prefectures = [
    { code: 1, label: '北海道' },
    { code: 2, label: '青森県' },
    { code: 3, label: '岩手県' },
    { code: 4, label: '宮城県' },
    { code: 5, label: '秋田県' },
    { code: 6, label: '山形県' },
    { code: 7, label: '福島県' },
    { code: 8, label: '茨城県' },
    { code: 9, label: '栃木県' },
    { code: 10, label: '群馬県' },
    { code: 11, label: '埼玉県' },
    { code: 12, label: '千葉県' },
    { code: 13, label: '東京都' },
    { code: 14, label: '神奈川県' },
    { code: 15, label: '新潟県' },
    { code: 16, label: '富山県' },
    { code: 17, label: '石川県' },
    { code: 18, label: '福井県' },
    { code: 19, label: '山梨県' },
    { code: 20, label: '長野県' },
    { code: 21, label: '岐阜県' },
    { code: 22, label: '静岡県' },
    { code: 23, label: '愛知県' },
    { code: 24, label: '三重県' },
    { code: 25, label: '滋賀県' },
    { code: 26, label: '京都府' },
    { code: 27, label: '大阪府' },
    { code: 28, label: '兵庫県' },
    { code: 29, label: '奈良県' },
    { code: 30, label: '和歌山県' },
    { code: 31, label: '鳥取県' },
    { code: 32, label: '島根県' },
    { code: 33, label: '岡山県' },
    { code: 34, label: '広島県' },
    { code: 35, label: '山口県' },
    { code: 36, label: '徳島県' },
    { code: 37, label: '香川県' },
    { code: 38, label: '愛媛県' },
    { code: 39, label: '高知県' },
    { code: 40, label: '福岡県' },
    { code: 41, label: '佐賀県' },
    { code: 42, label: '長崎県' },
    { code: 43, label: '熊本県' },
    { code: 44, label: '大分県' },
    { code: 45, label: '宮崎県' },
    { code: 46, label: '鹿児島県' },
    { code: 47, label: '沖縄県' },
  ];
  for (const { code, label } of prefectures) {
    lines.push(`  '${code}': '${label}',`);
  }
  lines.push('};');
  lines.push('');

  // Generate static enum data (nested structure, only schema enums)
  lines.push('const STATIC_ENUMS: EnumOptions = {');
  for (const [objectName, propsMap] of enumsByObject.entries()) {
    lines.push(`  ${objectName}: {`);
    for (const [propertyName, enumInfo] of propsMap.entries()) {
      lines.push(`    ${propertyName}: {`);
      for (const { value, label } of enumInfo.values) {
        lines.push(`      ${value}: '${label}',`);
      }
      lines.push(`    },`);
    }
    lines.push('  },');
  }
  lines.push('};');
  lines.push('');

  // Generate context
  lines.push('export interface EnumsContextType {');
  lines.push('  enums: EnumOptions | null;');
  lines.push('  loading: boolean;');
  lines.push('  error: Error | null;');
  lines.push('  /**');
  lines.push('   * Get label by object name, property name, and value');
  lines.push('   * @example getLabel("ApplicationForm", "account_type", "ORDINARY") // "普通"');
  lines.push('   */');
  lines.push('  getLabel: <T extends EnumObjectName>(objectName: T, propertyName: EnumPropertyName<T>, value: string | number) => string | undefined;');
  lines.push('  /**');
  lines.push('   * Get value by object name, property name, and label');
  lines.push('   * @example getValue("ApplicationForm", "account_type", "普通") // "ORDINARY"');
  lines.push('   */');
  lines.push('  getValue: <T extends EnumObjectName>(objectName: T, propertyName: EnumPropertyName<T>, label: string) => string | undefined;');
  lines.push('  /**');
  lines.push('   * Get select options by object name and property name');
  lines.push('   * @example getOptions("ApplicationForm", "account_type") // [{ value: "ORDINARY", label: "普通" }, ...]');
  lines.push('   */');
  lines.push('  getOptions: <T extends EnumObjectName>(objectName: T, propertyName: EnumPropertyName<T>) => { value: string; label: string }[];');
  lines.push('  /**');
  lines.push('   * Get prefecture options');
  lines.push('   * @example getPrefectures() // [{ value: "1", label: "北海道" }, ...]');
  lines.push('   */');
  lines.push('  getPrefectures: () => { value: string; label: string }[];');
  lines.push('  /**');
  lines.push('   * Get prefecture options with numeric values');
  lines.push('   * @example getPrefecturesAsNumbers() // [{ value: 1, label: "北海道" }, ...]');
  lines.push('   */');
  lines.push('  getPrefecturesAsNumbers: () => { value: number; label: string }[];');
  lines.push('}');
  lines.push('');
  lines.push('const EnumsContext = createContext<EnumsContextType | undefined>(undefined);');
  lines.push('');
  lines.push('export function EnumsProvider({ children }: { children: ReactNode }) {');
  lines.push('  const [enums] = useState<EnumOptions>(STATIC_ENUMS);');
  lines.push('  const [loading] = useState(false);');
  lines.push('  const [error] = useState<Error | null>(null);');
  lines.push('');
  lines.push('  const getLabel = useCallback(<T extends EnumObjectName>(objectName: T, propertyName: EnumPropertyName<T>, value: string | number): string | undefined => {');
  lines.push('    if (!enums) return undefined;');
  lines.push('    // Special case for prefectures');
  lines.push('    if (objectName === \'prefectures\' as any) {');
  lines.push('      return (enums as any).prefectures?.[String(value)];');
  lines.push('    }');
  lines.push('    const enumData = enums[objectName]?.[propertyName] as Record<string, string> | undefined;');
  lines.push('    if (!enumData) return undefined;');
  lines.push('    return enumData[String(value)];');
  lines.push('  }, [enums]);');
  lines.push('');
  lines.push('  const getValue = useCallback(<T extends EnumObjectName>(objectName: T, propertyName: EnumPropertyName<T>, label: string): string | undefined => {');
  lines.push('    if (!enums) return undefined;');
  lines.push('    // Special case for prefectures');
  lines.push('    if (objectName === \'prefectures\' as any) {');
  lines.push('      return Object.entries((enums as any).prefectures || {}).find(([_, l]) => l === label)?.[0];');
  lines.push('    }');
  lines.push('    const enumData = enums[objectName]?.[propertyName] as Record<string, string> | undefined;');
  lines.push('    if (!enumData) return undefined;');
  lines.push('    return Object.entries(enumData).find(([_, l]) => l === label)?.[0];');
  lines.push('  }, [enums]);');
  lines.push('');
  lines.push('  const getOptions = useCallback(<T extends EnumObjectName>(objectName: T, propertyName: EnumPropertyName<T>): { value: string; label: string }[] => {');
  lines.push('    if (!enums) return [];');
  lines.push('    const enumData = enums[objectName]?.[propertyName] as Record<string, string> | undefined;');
  lines.push('    if (!enumData) return [];');
  lines.push('    return Object.entries(enumData).map(([value, label]) => ({ value, label }));');
  lines.push('  }, [enums]);');
  lines.push('');
  lines.push('  const getPrefectures = useCallback((): { value: string; label: string }[] => {');
  lines.push('    return Object.entries(PREFECTURES).map(([value, label]) => ({ value, label }));');
  lines.push('  }, []);');
  lines.push('');
  lines.push('  const getPrefecturesAsNumbers = useCallback((): { value: number; label: string }[] => {');
  lines.push('    return Object.entries(PREFECTURES).map(([value, label]) => ({ value: Number(value), label }));');
  lines.push('  }, []);');
  lines.push('');
  lines.push('  return (');
  lines.push('    <EnumsContext.Provider');
  lines.push('      value={{');
  lines.push('        enums,');
  lines.push('        loading,');
  lines.push('        error,');
  lines.push('        getLabel,');
  lines.push('        getValue,');
  lines.push('        getOptions,');
  lines.push('        getPrefectures,');
  lines.push('        getPrefecturesAsNumbers,');
  lines.push('      }}');
  lines.push('    >');
  lines.push('      {children}');
  lines.push('    </EnumsContext.Provider>');
  lines.push('  );');
  lines.push('}');
  lines.push('');
  lines.push('export function useEnums(): EnumsContextType {');
  lines.push('  const context = useContext(EnumsContext);');
  lines.push('  if (context === undefined) {');
  lines.push("    throw new Error('useEnums must be used within an EnumsProvider');");
  lines.push('  }');
  lines.push('  return context;');
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

