import { EnumInfo } from './enumGenerator';

export function generateEnumContextFile(enums: EnumInfo[]): string {
  const lines: string[] = [];

  lines.push("'use client';");
  lines.push('');
  lines.push('// Auto-generated by @omnifyjp/omnify');
  lines.push('// Do not edit this file manually');
  lines.push('');
  lines.push("import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';");
  lines.push('');

  // Group by property name
  const enumsByProperty = new Map<string, EnumInfo[]>();
  for (const enumInfo of enums) {
    const key = enumInfo.propertyName;
    if (!enumsByProperty.has(key)) {
      enumsByProperty.set(key, []);
    }
    enumsByProperty.get(key)!.push(enumInfo);
  }

  // Generate EnumOptions interface
  lines.push('export interface EnumOptions {');
  for (const propertyName of enumsByProperty.keys()) {
    lines.push(`  ${propertyName}: Record<string, string>;`);
  }
  lines.push('  prefectures: Record<string, string>;');
  lines.push('}');
  lines.push('');

  // Generate static enum data
  lines.push('const STATIC_ENUMS: EnumOptions = {');
  for (const [propertyName, enumInfos] of enumsByProperty.entries()) {
    const values = enumInfos[0].values;
    lines.push(`  ${propertyName}: {`);
    for (const { value, label } of values) {
      lines.push(`    ${value}: '${label}',`);
    }
    lines.push('  },');
  }

  // Add prefectures
  lines.push('  prefectures: {');
  const prefectures = [
    { code: 1, label: '北海道' },
    { code: 2, label: '青森県' },
    { code: 3, label: '岩手県' },
    { code: 4, label: '宮城県' },
    { code: 5, label: '秋田県' },
    { code: 6, label: '山形県' },
    { code: 7, label: '福島県' },
    { code: 8, label: '茨城県' },
    { code: 9, label: '栃木県' },
    { code: 10, label: '群馬県' },
    { code: 11, label: '埼玉県' },
    { code: 12, label: '千葉県' },
    { code: 13, label: '東京都' },
    { code: 14, label: '神奈川県' },
    { code: 15, label: '新潟県' },
    { code: 16, label: '富山県' },
    { code: 17, label: '石川県' },
    { code: 18, label: '福井県' },
    { code: 19, label: '山梨県' },
    { code: 20, label: '長野県' },
    { code: 21, label: '岐阜県' },
    { code: 22, label: '静岡県' },
    { code: 23, label: '愛知県' },
    { code: 24, label: '三重県' },
    { code: 25, label: '滋賀県' },
    { code: 26, label: '京都府' },
    { code: 27, label: '大阪府' },
    { code: 28, label: '兵庫県' },
    { code: 29, label: '奈良県' },
    { code: 30, label: '和歌山県' },
    { code: 31, label: '鳥取県' },
    { code: 32, label: '島根県' },
    { code: 33, label: '岡山県' },
    { code: 34, label: '広島県' },
    { code: 35, label: '山口県' },
    { code: 36, label: '徳島県' },
    { code: 37, label: '香川県' },
    { code: 38, label: '愛媛県' },
    { code: 39, label: '高知県' },
    { code: 40, label: '福岡県' },
    { code: 41, label: '佐賀県' },
    { code: 42, label: '長崎県' },
    { code: 43, label: '熊本県' },
    { code: 44, label: '大分県' },
    { code: 45, label: '宮崎県' },
    { code: 46, label: '鹿児島県' },
    { code: 47, label: '沖縄県' },
  ];
  for (const { code, label } of prefectures) {
    lines.push(`    '${code}': '${label}',`);
  }
  lines.push('  },');

  lines.push('};');
  lines.push('');

  // Generate context
  lines.push('interface EnumsContextType {');
  lines.push('  enums: EnumOptions | null;');
  lines.push('  loading: boolean;');
  lines.push('  error: Error | null;');
  lines.push('  getLabel: (enumKey: keyof EnumOptions, value: string | number) => string | undefined;');
  lines.push('  getValue: (enumKey: keyof EnumOptions, label: string) => string | undefined;');
  lines.push('  getOptions: (enumKey: keyof EnumOptions) => { value: string; label: string }[];');
  lines.push('}');
  lines.push('');
  lines.push('const EnumsContext = createContext<EnumsContextType | undefined>(undefined);');
  lines.push('');
  lines.push('export function EnumsProvider({ children }: { children: ReactNode }) {');
  lines.push('  const [enums] = useState<EnumOptions>(STATIC_ENUMS);');
  lines.push('  const [loading] = useState(false);');
  lines.push('  const [error] = useState<Error | null>(null);');
  lines.push('');
  lines.push('  const getLabel = (enumKey: keyof EnumOptions, value: string | number): string | undefined => {');
  lines.push('    if (!enums) return undefined;');
  lines.push('    const enumData = enums[enumKey];');
  lines.push('    if (!enumData) return undefined;');
  lines.push('    return enumData[String(value)];');
  lines.push('  };');
  lines.push('');
  lines.push('  const getValue = (enumKey: keyof EnumOptions, label: string): string | undefined => {');
  lines.push('    if (!enums) return undefined;');
  lines.push('    const enumData = enums[enumKey];');
  lines.push('    if (!enumData) return undefined;');
  lines.push('    return Object.entries(enumData).find(([_, l]) => l === label)?.[0];');
  lines.push('  };');
  lines.push('');
  lines.push('  const getOptions = (enumKey: keyof EnumOptions): { value: string; label: string }[] => {');
  lines.push('    if (!enums) return [];');
  lines.push('    const enumData = enums[enumKey];');
  lines.push('    if (!enumData) return [];');
  lines.push('    return Object.entries(enumData).map(([value, label]) => ({ value, label }));');
  lines.push('  };');
  lines.push('');
  lines.push('  return (');
  lines.push('    <EnumsContext.Provider');
  lines.push('      value={{');
  lines.push('        enums,');
  lines.push('        loading,');
  lines.push('        error,');
  lines.push('        getLabel,');
  lines.push('        getValue,');
  lines.push('        getOptions,');
  lines.push('      }}');
  lines.push('    >');
  lines.push('      {children}');
  lines.push('    </EnumsContext.Provider>');
  lines.push('  );');
  lines.push('}');
  lines.push('');
  lines.push('export function useEnums(): EnumsContextType {');
  lines.push('  const context = useContext(EnumsContext);');
  lines.push('  if (context === undefined) {');
  lines.push("    throw new Error('useEnums must be used within an EnumsProvider');");
  lines.push('  }');
  lines.push('  return context;');
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

