import * as fs from 'fs';
import * as path from 'path';

export function generateUseFormSubmitHook(): string {
    const lines: string[] = [];

    lines.push("'use client';");
    lines.push('');
    lines.push('// Auto-generated by @famgia/omnify');
    lines.push('// Do not edit this file manually');
    lines.push('');
    lines.push("import { useState } from 'react';");
    lines.push("import { FormInstance, App } from 'antd';");
    lines.push("import { getCsrfCookie } from '../lib/axios';");
    lines.push('');
    lines.push('export interface UseFormSubmitOptions<TResponse = any> {');
    lines.push('  form: FormInstance;');
    lines.push('  submitFn: (values: any) => Promise<TResponse>;');
    lines.push('  onSuccess?: (response: TResponse, values: any) => void | Promise<void>;');
    lines.push('  onError?: (error: any, values: any) => void | Promise<void>;');
    lines.push('  withCsrf?: boolean;');
    lines.push('  errorMessages?: {');
    lines.push('    500?: string;');
    lines.push('    401?: string;');
    lines.push('    403?: string;');
    lines.push('    default?: string;');
    lines.push('  };');
    lines.push('}');
    lines.push('');
    lines.push('export interface UseFormSubmitResult {');
    lines.push('  handleSubmit: (values: any) => Promise<void>;');
    lines.push('  loading: boolean;');
    lines.push('  setLoading: (loading: boolean) => void;');
    lines.push('}');
    lines.push('');
    lines.push('/**');
    lines.push(' * Custom hook for handling form submission with automatic Laravel validation error mapping');
    lines.push(' */');
    lines.push('export function useFormSubmit<TResponse = any>(');
    lines.push('  options: UseFormSubmitOptions<TResponse>');
    lines.push('): UseFormSubmitResult {');
    lines.push('  const {');
    lines.push('    form,');
    lines.push('    submitFn,');
    lines.push('    onSuccess,');
    lines.push('    onError,');
    lines.push('    withCsrf = true,');
    lines.push('    errorMessages = {},');
    lines.push('  } = options;');
    lines.push('');
    lines.push('  const [loading, setLoading] = useState(false);');
    lines.push('  const { message: messageApi } = App.useApp();');
    lines.push('');
    lines.push('  const handleSubmit = async (values: any): Promise<void> => {');
    lines.push('    setLoading(true);');
    lines.push('    try {');
    lines.push('      if (withCsrf) {');
    lines.push('        await getCsrfCookie();');
    lines.push('      }');
    lines.push('');
    lines.push('      const response = await submitFn(values);');
    lines.push('');
    lines.push('      if (onSuccess) {');
    lines.push('        await onSuccess(response, values);');
    lines.push('      }');
    lines.push('    } catch (error: any) {');
    lines.push("      console.error('Form submission error:', error);");
    lines.push('');
    lines.push('      if (onError) {');
    lines.push('        await onError(error, values);');
    lines.push('        return;');
    lines.push('      }');
    lines.push('');
    lines.push('      // Handle validation errors (422)');
    lines.push('      if (error.response?.status === 422 && error.response?.data?.errors) {');
    lines.push('        const errors = error.response.data.errors;');
    lines.push('');
    lines.push('        // Set field errors');
    lines.push('        const formErrors = Object.keys(errors).map((field) => ({');
    lines.push('          name: field,');
    lines.push('          errors: errors[field],');
    lines.push('        }));');
    lines.push('        form.setFields(formErrors);');
    lines.push('');
    lines.push('        // Show error message');
    lines.push('        const errorCount = Object.keys(errors).length;');
    lines.push('        const errorList = Object.values(errors)');
    lines.push('          .map((msgs: any) => msgs[0])');
    lines.push("          .join(' / ');");
    lines.push('');
    lines.push('        messageApi.error({');
    lines.push('          content: `入力内容にエラーがあります（${errorCount}件）: ${errorList}`,');
    lines.push('          duration: 8,');
    lines.push('        });');
    lines.push('');
    lines.push("        console.error('Validation errors:', errors);");
    lines.push('      }');
    lines.push('      // Handle server errors');
    lines.push('      else if (error.response?.status >= 500) {');
    lines.push('        messageApi.error(');
    lines.push("          errorMessages[500] || 'サーバーエラーが発生しました。しばらくしてから再度お試しください。'");
    lines.push('        );');
    lines.push('      }');
    lines.push('      // Handle auth errors');
    lines.push('      else if (error.response?.status === 401 || error.response?.status === 403) {');
    lines.push('        const status = error.response.status as 401 | 403;');
    lines.push('        messageApi.error(');
    lines.push("          errorMessages[status] || '認証エラーが発生しました。再度ログインしてください。'");
    lines.push('        );');
    lines.push('      }');
    lines.push('      // Handle generic errors');
    lines.push('      else {');
    lines.push('        messageApi.error(');
    lines.push("          error.response?.data?.message || errorMessages.default || '送信に失敗しました'");
    lines.push('        );');
    lines.push('      }');
    lines.push('    } finally {');
    lines.push('      setLoading(false);');
    lines.push('    }');
    lines.push('  };');
    lines.push('');
    lines.push('  return {');
    lines.push('    handleSubmit,');
    lines.push('    loading,');
    lines.push('    setLoading,');
    lines.push('  };');
    lines.push('}');
    lines.push('');

    return lines.join('\n');
}

export function generateAxiosLib(): string {
    const lines: string[] = [];

    lines.push('// Auto-generated by @famgia/omnify');
    lines.push('// Do not edit this file manually');
    lines.push('');
    lines.push("import axios, { AxiosError, InternalAxiosRequestConfig } from 'axios';");
    lines.push('');
  lines.push('// Validate required environment variable');
  lines.push('if (!process.env.NEXT_PUBLIC_API_URL) {');
  lines.push("  throw new Error('NEXT_PUBLIC_API_URL environment variable is required');");
  lines.push('}');
  lines.push('');
  lines.push('// Create axios instance');
  lines.push('const axiosInstance = axios.create({');
  lines.push('  baseURL: process.env.NEXT_PUBLIC_API_URL,');
  lines.push('  timeout: 30000,');
    lines.push('  withCredentials: true,');
    lines.push('  headers: {');
    lines.push("    'Accept': 'application/json',");
    lines.push("    'Content-Type': 'application/json',");
    lines.push('  },');
    lines.push("  xsrfCookieName: 'XSRF-TOKEN',");
    lines.push("  xsrfHeaderName: 'X-XSRF-TOKEN',");
    lines.push('});');
    lines.push('');
    lines.push('// Helper to get cookie value by name');
    lines.push('function getCookie(name: string): string | null {');
    lines.push("  if (typeof document === 'undefined') return null;");
    lines.push('  const value = `; ${document.cookie}`;');
    lines.push('  const parts = value.split(`; ${name}=`);');
    lines.push("  if (parts.length === 2) return parts.pop()?.split(';').shift() || null;");
    lines.push('  return null;');
    lines.push('}');
    lines.push('');
    lines.push('// Request interceptor');
    lines.push('axiosInstance.interceptors.request.use(');
    lines.push('  (config: InternalAxiosRequestConfig) => {');
    lines.push("    const token = getCookie('XSRF-TOKEN');");
    lines.push('    if (token) {');
    lines.push("      config.headers['X-XSRF-TOKEN'] = decodeURIComponent(token);");
    lines.push('    }');
    lines.push('    return config;');
    lines.push('  },');
    lines.push('  (error: AxiosError) => {');
    lines.push('    return Promise.reject(error);');
    lines.push('  }');
    lines.push(');');
    lines.push('');
    lines.push('/**');
    lines.push(' * Get CSRF cookie before making authenticated requests');
  lines.push(' * Required for Laravel Sanctum cookie-based authentication');
  lines.push(' */');
  lines.push('export const getCsrfCookie = async (): Promise<void> => {');
  lines.push('  if (!process.env.NEXT_PUBLIC_API_URL) {');
  lines.push("    throw new Error('NEXT_PUBLIC_API_URL environment variable is required');");
  lines.push('  }');
  lines.push('  await axiosInstance.get(`${process.env.NEXT_PUBLIC_API_URL}/sanctum/csrf-cookie`);');
  lines.push('};');
    lines.push('');
    lines.push('export default axiosInstance;');
    lines.push('');

    return lines.join('\n');
}

export function generateHooksAndLib(outputDir: string): void {
    const hooksDir = path.join(outputDir, 'hooks');
    const libDir = path.join(outputDir, 'lib');

    // Create directories
    if (!fs.existsSync(hooksDir)) {
        fs.mkdirSync(hooksDir, { recursive: true });
    }
    if (!fs.existsSync(libDir)) {
        fs.mkdirSync(libDir, { recursive: true });
    }

    // Generate useFormSubmit hook
    const useFormSubmitContent = generateUseFormSubmitHook();
    fs.writeFileSync(path.join(hooksDir, 'useFormSubmit.tsx'), useFormSubmitContent);
    console.log('✅ Generated hooks/useFormSubmit.tsx');

    // Generate hooks index
    const hooksIndexContent = [
        '// Auto-generated by @famgia/omnify',
        "export * from './useFormSubmit';",
        '',
    ].join('\n');
    fs.writeFileSync(path.join(hooksDir, 'index.ts'), hooksIndexContent);
    console.log('✅ Generated hooks/index.ts');

    // Generate axios lib
    const axiosContent = generateAxiosLib();
    fs.writeFileSync(path.join(libDir, 'axios.ts'), axiosContent);
    console.log('✅ Generated lib/axios.ts');

    // Generate lib index
    const libIndexContent = [
        '// Auto-generated by @famgia/omnify',
        "export { default as axios, getCsrfCookie } from './axios';",
        '',
    ].join('\n');
    fs.writeFileSync(path.join(libDir, 'index.ts'), libIndexContent);
    console.log('✅ Generated lib/index.ts');
}

