#!/usr/bin/env node

import * as fs from 'fs';
import * as path from 'path';
import { SchemaLock } from './types';
import { extractEnums, generateEnumsFile } from './generators/enumGenerator';
import { generateAllModels } from './generators/modelGenerator';
import { generateEnumContextFile } from './generators/contextGenerator';

interface BuildOptions {
  schemaPath: string;
  outputDir: string;
  watch?: boolean;
}

function build(options: BuildOptions) {
  const { schemaPath, outputDir } = options;

  console.log('\n🔨 Building Omnify types...');

  // Check if schema exists
  if (!fs.existsSync(schemaPath)) {
    console.error(`❌ Error: Schema file not found at ${schemaPath}`);
    console.error('\nUsage:');
    console.error('  omnify-build --schema <path> --output <dir>');
    process.exit(1);
  }

  try {
    // Read schema
    const schemaContent = fs.readFileSync(schemaPath, 'utf-8');
    const schema: SchemaLock = JSON.parse(schemaContent);

    // Create output directories
    const typesDir = path.join(outputDir, 'types');
    const contextsDir = path.join(outputDir, 'contexts');

    [typesDir, contextsDir].forEach(dir => {
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }
    });

    // Extract enums
    const enums = extractEnums(schema);
    console.log(`📦 Found ${enums.length} enum properties`);

    // Generate enums (types + options in one file)
    const enumsContent = generateEnumsFile(enums);
    fs.writeFileSync(path.join(typesDir, 'enums.ts'), enumsContent);
    console.log('✅ Generated types/enums.ts');

    // Generate models
    const modelsContent = generateAllModels(schema);
    fs.writeFileSync(path.join(typesDir, 'models.ts'), modelsContent);
    console.log('✅ Generated types/models.ts');

    // Generate enum context
    const contextContent = generateEnumContextFile(enums);
    fs.writeFileSync(path.join(contextsDir, 'EnumsContext.tsx'), contextContent);
    console.log('✅ Generated contexts/EnumsContext.tsx');

    // Generate index files
    const typesIndexContent = `// Auto-generated by @omnifyjp/omnify
export * from './enums';
export * from './enumOptions';
export * from './models';
`;
    fs.writeFileSync(path.join(typesDir, 'index.ts'), typesIndexContent);
    console.log('✅ Generated types/index.ts');

    const contextsIndexContent = `// Auto-generated by @omnifyjp/omnify
export * from './EnumsContext';
`;
    fs.writeFileSync(path.join(contextsDir, 'index.ts'), contextsIndexContent);
    console.log('✅ Generated contexts/index.ts');

    const mainIndexContent = `// Auto-generated by @omnifyjp/omnify
export * from './types';
export * from './contexts';
`;
    fs.writeFileSync(path.join(outputDir, 'index.ts'), mainIndexContent);
    console.log('✅ Generated index.ts');

    console.log(`\n✨ Generated files in: ${outputDir}\n`);
  } catch (error: any) {
    console.error('\n❌ Error:', error.message);
    process.exit(1);
  }
}

function watch(options: BuildOptions) {
  console.log(`\n👀 Watching ${options.schemaPath}...\n`);

  // Initial build
  build(options);

  // Watch for changes
  const chokidar = require('chokidar');
  const watcher = chokidar.watch(options.schemaPath, {
    persistent: true,
    ignoreInitial: true,
  });

  watcher.on('change', () => {
    console.log('\n🔄 Schema changed, rebuilding...');
    build(options);
  });

  watcher.on('error', (error: any) => {
    console.error('❌ Watcher error:', error);
  });

  // Handle graceful shutdown
  process.on('SIGINT', () => {
    console.log('\n\n👋 Stopping...');
    watcher.close();
    process.exit(0);
  });
}

// CLI
const args = process.argv.slice(2);

if (args.length === 0 || args.includes('--help') || args.includes('-h')) {
  console.log('omnify-build - Convert Omnify .omnify/schema-lock.json to TypeScript types');
  console.log('');
  console.log('Usage:');
  console.log('  omnify-build [--schema <path>] --output <dir> [--watch]');
  console.log('');
  console.log('Options:');
  console.log('  --schema <path>   Path to schema-lock.json (optional, auto-detect from .omnify/)');
  console.log('  --output <dir>    Output directory (required)');
  console.log('  --watch           Watch for schema changes');
  console.log('  --help, -h        Show this help');
  console.log('');
  console.log('Auto-detection paths (in order):');
  console.log('  1. ../backend/.omnify/schema-lock.json  (from frontend)');
  console.log('  2. ./backend/.omnify/schema-lock.json   (from root)');
  console.log('  3. ./.omnify/schema-lock.json           (current dir)');
  console.log('');
  console.log('Examples:');
  console.log('  omnify-build --output src/omnify                                      # Auto-detect schema');
  console.log('  omnify-build --schema backend/.omnify/schema-lock.json --output src/omnify');
  console.log('  omnify-build --output src/omnify --watch                              # Auto-detect + watch');
  process.exit(args.length === 0 ? 1 : 0);
}

// Parse arguments
let schemaPath: string | null = null;
let outputDir: string | null = null;
let watchMode = args.includes('--watch');

for (let i = 0; i < args.length; i++) {
  if (args[i] === '--schema' && i + 1 < args.length) {
    schemaPath = path.resolve(args[i + 1]);
    i++;
  } else if (args[i] === '--output' && i + 1 < args.length) {
    outputDir = path.resolve(args[i + 1]);
    i++;
  }
}

// Auto-detect schema path if not provided
if (!schemaPath) {
  const possiblePaths = [
    path.resolve('../backend/.omnify/schema-lock.json'),  // Priority: backend from frontend
    path.resolve('backend/.omnify/schema-lock.json'),      // Priority: backend from root
    path.resolve('.omnify/schema-lock.json'),              // Fallback: current directory
  ];

  for (const possiblePath of possiblePaths) {
    if (fs.existsSync(possiblePath)) {
      schemaPath = possiblePath;
      console.log(`📍 Auto-detected schema at: ${possiblePath}`);
      break;
    }
  }

  if (!schemaPath) {
    console.error('❌ Error: Could not find schema-lock.json');
    console.error('\nSearched in:');
    possiblePaths.forEach(p => console.error(`  - ${p}`));
    console.error('\nPlease specify with --schema <path>');
    console.error('\nUsage:');
    console.error('  omnify-build --schema <path> --output <dir>');
    process.exit(1);
  }
}

if (!outputDir) {
  console.error('❌ Error: --output is required');
  console.error('\nUsage:');
  console.error('  omnify-build --schema <path> --output <dir>');
  process.exit(1);
}

const options: BuildOptions = {
  schemaPath,
  outputDir,
  watch: watchMode,
};

if (watchMode) {
  watch(options);
} else {
  build(options);
}
